# 测试

## How to Write Tests

测试：

- 函数

- 验证非测试代码的功能是否和预期一致

测试函数体（通常）执行的3个操作：

- 准备数据/状态
- 运行被测试的代码一断言（Assert）结果

解剖测试函数

测试函数需要使用 test 属性（attribute）进行标注

- Attribute 就是一段 Rust 代码的元数据
- 在函数上加 `# [test]`，可把函数变成测试函数

运行测试

使用 cargo test 命令运行所有测试函数

- Rust 会构建一个 Test Runner 可执行文件
    - 它会运行标注了 test 的函数，并报告其运行是否成功

- 当使用 cargo 创建 library 项目的时候，会生成一个 test module，里面有一个 test 函数
    - 你可以添加任意数量的 test module 或函数

举例：

```rust
pub fn add(left: usize, right: usize) -> usize {
    left + right
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn it_works() { // 这就是一个测试函数
        let result = add(2, 2);
        assert_eq!(result, 4);
    }
}
```

测试失败

- 测试函数 panic 就表示失败。每个测试运行在一个新线程。

- 当主线程看见某个测试线程挂掉了，那个测试标记为失败了。

```rust
#[test]
fn another() { // 该函数会因为恐慌而失败
    panic!("make this fn panic!");
}
```

## `assert!` Macro

使用 `assert!` 宏检查测试结果

`assert!` 宏，来自标准库，用来确定某个状态是否为 true

- true：测试通过

- false：调用 `panic!`，发生恐慌，测试失败

```rust
#[derive(Debug)]
struct Rectangle {
    width: u32,
    height: u32,
}

impl Rectangle {
    fn can_hold(&self, other: &Rectangle) -> bool {
        self.width > other.width && self.height > other.height
    }
}

#[cfg(test)]
mod tests {
    use super::*; // 导入模块外部的东西

    #[test]
    fn larger_can_hold_smaller() {
        let larger = Rectangle {
            width: 8,
            height: 7,
        };
        let smaller = Rectangle {
            width: 5,
            height: 1,
        };

        assert!(larger.can_hold(&smaller)); // 断言测试，bool 值决定是否 panic
    }
}
```

使用 `assert_eq!` 和 `assert_ne!` 测试相等性

- 都来自标准库
- 判断两个参数是否相等或不等
- 实际上，它们使用的就是 `==` 和 `!=` 运算符

- 断言失败：自动打印出两个参数的值
    - 使用 debug 格式打印参数
    - 要求参数实现了 `PartialEq` 和 `Debug Traits`（所有的基本类型和标准库里大部分类型都实现了）

```rust
pub fn add_two(a: i32) -> i32 {
    a + 2
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn it_adds_two() {
        assert_eq!(4, add_two(2)); // 参数位置可以调换
    }
}
```

## 自定义错误消息

Adding Custom Failure Messages

可以向 `assert!`、`assert_eq!`、`assert_ne`! 添加可选的自定义消息一这些自定义消息和失败消息都会打印出来
- `assert!`：第1参数必填，自定义消息作为第2个参数。
- `assert_eq! ` 和 `assert_ne!`：前2个参数必填，自定义消息作为第3个参数。
- 自定义消息参数会被传递给 `format!` 宏，可以使用占位符

```rust
pub fn greeting(name: &str) -> String {
    format!("Hello {}!", name)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn greeting_contains_name() {
        let result = greeting("Carol");
        assert!(
        	result.contains("Carol"),
            "Greeting did not contain name, value was `{}`",
            result // 这些自定义信息将会传给 format!
        );
    }
}
```

## `should_panic`

Checking for Panics with `should_panic`

验证错误处理的情况

测试除了验证代码的返回值是否正确，还需验证代码是否如预期的处理了发生错误
的情况。

可验证代码在特定情况下是否发生了 panic

should_panic 属性：

- 函数 panic：测试通过
- 函数没有panic：测试失败

```rust
pub struct Guess {
    value: i32,
}

impl Guess {
    pub fn new(value: i32) -> Guess {
        if value < 1 || value > 100 {
            panic!("Guess value must be between 1 and 100, got {}.", value);
        }

        Guess { value }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    #[should_panic]
    fn greater_than_100() {
        Guess::new(200); // 因为传入的是200，会发生恐慌 而且如果函数没有恐慌，则测试失败
    }
}
```

让 should_panic 更精确

为 should_panic 属性添加一个可选的 expected 参数：

- 将检查失败消息中是否包含所指定的文字

```rust
pub struct Guess {
    value: i32,
}

// --snip--

impl Guess {
    pub fn new(value: i32) -> Guess {
        if value < 1 {
            panic!(
                "Guess value must be greater than or equal to 1, got {}.",
                value
            );
        } else if value > 100 {
            panic!(
                "Guess value must be less than or equal to 100, got {}.",
                value
            );
        }

        Guess { value }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    #[should_panic(expected = "less than or equal to 100")]
    // 虽然发生了恐慌，但是我们让测试通过了
    fn greater_than_100() {
        Guess::new(200);
    }
}
```

在测试中使用 `Result<T,E>`

无需 panic，可使用 `Result<T,E>` 作为返回类型编写测试：

- 返回 `Ok`：测试通过
- 返回 `Err`：测试失败

```rust
#[cfg(test)]
mod tests {
    #[test]
    fn it_works() -> Result<(), String> { // 注意返回值
        if 2 + 2 == 4 {
            Ok(())
        } else {
            Err(String::from("two plus two does not equal four"))
        }
    }
}
```

